[book]
title = "Rust dasturlash tili"
authors = ["Steve Klabnik", "Carol Nichols", "Contributions from the Rust Community", "Malikov Suhrob"]

[output.html]
additional-css = ["ferris.css", "theme/2018-edition.css"]
additional-js = ["ferris.js"]
git-repository-url = "https://github.com/mlkvdev/book"
